version: '3'

services:
  db:
    image: postgres:14.5
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./databases/:/databases/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  graphql-api:
      restart: always
      build:
        context: ./services/graphql-api
      depends_on:
        - db
      ports:
        - 5433:5433
      environment:
        - db_uri=postgres://postgres@db:5432/dev

volumes:
  db_volume:
    external: true